"""about me and last seen

Revision ID: 339b7a9ad96d
Revises: 8ebe93549793
Create Date: 2019-01-21 12:56:03.867540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339b7a9ad96d'
down_revision = '8ebe93549793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
